### ISSUE TITLE
Start mapping govt. heirarchy into a diagram

### ISSUE THREAD

**Issue by masnabinumeed** [codeforpakistan/design-system#11]
Objectives:

Organize parentage of ministries and their children depts visually
Using color-coding if possible
Focus on Federal first.
-> Ministries priority
-> 26 categories? Verify if 26 really needed
-> Ministry of IT as pilot

**Comment by retrospectionn** [comment]
Interested in doing this. Would love to get this sorted out. Will be either using Mira, Adobe XD or Figma. Depends on how easy it is to replicate data.

**Comment by masnabinumeed** [comment]
@retrospectionn sure thing. Can you ping me on Whatsapp and we can discuss how to go about this.

**Comment by retrospectionn** [comment]
**Objectives:**

- Organize parentage of ministries and their children depts visually
- Using color-coding if possible
- Focus on Federal first.
 -> Ministries priority
 -> 26 categories? Verify if 26 really needed
 -> Ministry of IT as pilot

**Comment by retrospectionn** [comment]
Rough version complete. Validation required next. @masnabinumeed can you allocate a new validation task to me? Thanks!
