### ISSUE TITLE
Map out Right to Information Act

### ISSUE THREAD

**Issue by masnabinumeed** [codeforpakistan/design-system#27]
Map out what the Right to Information Act 2017 outlines about the content to be added to government websites

https://pakistancode.gov.pk/english/UY2FqaJw1-apaUY2Fqa-apaUY2Noa5c%3D-sg-jjjjjjjjjjjjj

**Comment by masnabinumeed** [comment]
[Policy-Brief-Digitization-for-Improved-Public-Service-Delivery.pdf](https://github.com/user-attachments/files/17180905/Policy-Brief-Digitization-for-Improved-Public-Service-Delivery.pdf)

**Comment by projectzia** [comment]
Hi, add me as the assignee
