### ISSUE TITLE
Short list projects for pilot

### ISSUE THREAD

**Issue by masnabinumeed** [codeforpakistan/design-system#6]
Proposed for website:
1. [Ministry of Information Technology & Telecommunication](https://moitt.gov.pk/)
2. [Code for Pakistan](https://codeforpakistan.org/)

Proposed for web app:
1. Pehchan digital identity
2. Pakistan Citizen's Portal
3. [PTA Device Registration System](https://dirbs.pta.gov.pk/drs/individual/coc_details/18058898)

**Comment by masnabinumeed** [comment]
@schajee @aliirz Can you guys please finalize on this by today?

**Comment by schajee** [comment]
I think Ministry should be one, and then Pehchan

**Comment by masnabinumeed** [comment]
Alright lets go with MoITT and Pehchan
