### ISSUE TITLE
Collect artefacts for brand mood board

### ISSUE THREAD

**Issue by masnabinumeed** [codeforpakistan/design-system#8]
Use the following FigJam board to document:
https://www.figma.com/board/2tkIhbLUGpzxrWqNbHEkia/Moodboard?node-id=0-1&t=Hdk6C6XRUZpG6C0X-1

Add artefacts that reflect the pakistani identity. These can be:
- Symbology
- Cultural imagery
- Graphic Design
- Websites
- Typography

**Comment by Azeem115** [comment]
Would like to work on this task @masnabinumeed

**Comment by masnabinumeed** [comment]
@Azeem115 all yours!

**Comment by Azeem115** [comment]
Thanks! Just one teeny-tiny request. Can you please grant edit access to the FigJam board.

**Comment by projectzia** [comment]
Add me in as the assignee as well
