### ISSUE TITLE
Collect inspiration and examples for pilot projects

### ISSUE THREAD

**Issue by masnabinumeed** [codeforpakistan/design-system#9]
Use the following FigJam baord to collect inspirations for the pilot:
https://www.figma.com/board/2tkIhbLUGpzxrWqNbHEkia/Moodboard?node-id=0-1&t=Hdk6C6XRUZpG6C0X-1

These can include:
- Public websites
- e-government portals
- Mobile apps
- Design Systems

**Comment by HassaanBM** [comment]
I am volunteering to take on this task.

**Comment by masnabinumeed** [comment]
@HassaanBM all yours!

**Comment by projectzia** [comment]
Add me in as well as the assignee

**Comment by projectzia** [comment]
Hi, this is the account

**Comment by Boffins-5** [comment]
Salam, I want to volunteer for this project.
